In [2]:
import pandas as pd

df = pd.read_csv('./datasets/atlcrime.csv')
df

,Unnamed: 0,crime,number,date,location,beat,neighborhood,npu,lat,long
0,0,LARCENY-NON VEHICLE,103040029,10/31/2010,610 SPRING ST NW,509,Downtown,M,33.77101,-84.38895
1,1,AUTO THEFT,103040061,10/31/2010,850 OAK ST SW,401,West End,T,33.74057,-84.41680
2,2,LARCENY-FROM VEHICLE,103040169,10/31/2010,1344 METROPOLITAN PKWY SW,301,Capitol View Manor,X,33.71803,-84.40774
3,3,AUTO THEFT,103040174,10/31/2010,1752 PRYOR RD SW,307,Betmar LaVilla,Y,33.70731,-84.39674
4,4,LARCENY-NON VEHICLE,103040301,10/31/2010,JOHN WESLEY DOBBS AVE NE / CORLEY ST NE,604,Old Fourth Ward,M,33.75947,-84.36626
...,...,...,...,...,...,...,...,...,...,...
270683,270683,BURGLARY-RESIDENCE,92442142,09/01/2009,1226 PORTLAND AVE SE,612,East Atlanta,W,33.73927,-84.34741
270684,270684,LARCENY-FROM VEHICLE,92442164,09/01/2009,317 PICKFAIR WAY SW,307,Lakewood Heights,Y,33.70436,-84.40013
270685,270685,LARCENY-NON VEHICLE,92448045,09/01/2009,6234 SPINE RD @ATRIUM,50,NaN,NaN,33.64068,-84.44204
270686,270686,LARCENY-NON VEHICLE,92440866,09/01/2009,30 WARREN ST,610,Kirkwood,O,33.75374,-84.32600
270687,270687,HOMICIDE,92440372058,09/01/2009,2860 MARTIN L KING JR DR SW,405,Harland Terrace,I,33.75399,-84.48138